apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-test
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-test
  template:
    metadata:
      labels:
        app: devops-test
    spec:
      containers:
        - name: devops-test
          image: europe-west1-docker.pkg.dev/project-c5f72c1b-6454-456f-bc4/xp-repo/devops-test:bc7cf29
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: devops-test
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: devops-test
  ports:
    - name: http
      port: 80
      targetPort: 8080